#%%  import
#Calculation of table 1 of article #1
import sys
sys.path.append('/data8/projets/ChasseM_Compass_1013663/'+\
                'code/nsauthier/git_ChasseM_Compass_1013663/'+\
                'Clinical_Model/time_series_model/')
import pandas as pd, numpy as np
from DataCleaning import get_ICD10
            
output_dir ='/data8/projets/ChasseM_Compass_1013663/output/clinical_data'
file_name = "FINAL"
output_folder = output_dir+"/8_transplantqc_donors2020_ICUCARD/"

raw_ICD10_file = '6_medecho_ICD_diag_codes_tq_donors_2021-06-07.csv'


#Loading Data
static_final = pd.read_csv(output_folder+file_name+'_clean_static.csv')
ICD10 = get_ICD10(static_final, output_dir,raw_ICD10_file)

ICD10_brut = pd.read_csv(output_dir + '/6_medecho_ICD_diag_codes_tq_donors_2021-06-07.csv',
                         usecols = ['cddiagnostic', 'desctypediagnostic',
                                    'hospital_mrg','dw_pid', 'noadm_mrg'])
ICD10_brut.rename(columns = {'hospital_mrg':'hospital', 'noadm_mrg':'noadm'}, inplace=True)
ICD10_brut.dropna(subset=['cddiagnostic'], inplace=True)

#%% Code
#ICD10 text conversion
ICD10['letter'] = ICD10.cddiagnostic.str[0].apply(ord)
ICD10[['category', 'subcategory']] = ICD10.cddiagnostic.str[1:].str.split('.', expand=True)
ICD10['category'] = ICD10['category'].astype(int) + 100*(ICD10['letter']-ord('A'))
ICD10.drop(columns = 'letter', inplace=True)

#Chapters
ICD10['chapter'] = pd.cut(ICD10.category,
     bins = [0]+list(chapters_ICD10.keys()),
     labels = list(chapters_ICD10.values()))

ICD10['chapter_code'] = pd.cut(ICD10.category,
     bins = [0] + list(chapters_ICD10.keys()),
     labels = list(chapters_ICD10.keys()))


#Sub _Chapters
ICD10['sub_chapter'] = pd.cut(ICD10.category,
     bins = [0]+list(sub_chapters_ICD10.keys()),
     labels = list(sub_chapters_ICD10.values()))

ICD10['sub_chapter_code'] = pd.cut(ICD10.category,
     bins = [0]+list(sub_chapters_ICD10.keys()),
     labels = list(sub_chapters_ICD10.keys()))

#Add cardiac arrest
card_all = ICD10_brut[ICD10_brut.cddiagnostic.str.startswith('I46')]
card_all = card_all.drop_duplicates(['dw_pid', 'noadm']).dw_pid.unique()
card_principalDx = ICD10[ICD10.cddiagnostic.str.startswith('I46')]
card_principalDx = card_principalDx.drop_duplicates(['dw_pid','noadm']).dw_pid.unique()

ICD10['ACR_principalDx'] = 0
ICD10.loc[ICD10['dw_pid'].isin(card_principalDx), 'ACR_principalDx'] = 1
ICD10['ACR_in_all_Dx'] = 0
ICD10.loc[ICD10['dw_pid'].isin(card_all), 'ACR_in_all_Dx'] = 1

#Add Death and merge_inner 
ICD10 = ICD10.merge(static_final[['noadm', 'dw_pid', 'death_in_icu']],
                    on= ['dw_pid', 'noadm'],
                    how='inner')

#%% Print output for table 1

sec = (pd.to_datetime(static_final.dhrefin) - pd.to_datetime(static_final.dhredeb)).dt.seconds
day = (pd.to_datetime(static_final.dhrefin) - pd.to_datetime(static_final.dhredeb)).dt.days
static_final['los'] = day* 24 + sec/3600

values_df = []

subsets = [['AE_train_set'],
           ['train_set'],
           ['valid_set'],
           ['test_set'],
           ['train_set','valid_set','test_set'],
           ['valid_ucoro']]

for subset in subsets:
    sub_values = static_final[static_final.subset.isin(subset)]
    sub_ICD10 = ICD10[ICD10.subset.isin(subset)]
    
    dic = {'subset':subset,
           'Number of pt': len(sub_values),
           'Female sex N': (sub_values.sexe == 'F').sum(),
           'Female sex %': (sub_values.sexe == 'F').mean(),
           'Average age' : sub_values.age.mean(),
           'Std age' : sub_values.age.std(),
           'Proportion donor':sub_values.pdonor.mean(),
           'Proportion donor':sub_values.pdonor.sum(),
           'Donor subtypes':'',
           'Non donor %':(sub_values.donor_type == 'Non_donor').mean(),
           'Transfered for donation %':(sub_values.donor_type == 'Refered_Transfered_for_donation').mean(),
           'Local Donors %':(sub_values.donor_type == 'Refered_Donated').mean(),
           'Refused potential donors %':(sub_values.donor_type == 'Refered_Not_eligible').mean(),
           'Non refered potential donors %':(sub_values.donor_type == 'Not_refered').mean(),
           'Non donor':(sub_values.donor_type == 'Non_donor').sum(),
           'Transfered for donation':(sub_values.donor_type == 'Refered_Transfered_for_donation').sum(),
           'Local Donors':(sub_values.donor_type == 'Refered_Donated').sum(),
           'Refused potential donors':(sub_values.donor_type == 'Refered_Not_eligible').sum(),
           'Non refered potential donors':(sub_values.donor_type == 'Not_refered').sum(),
           'Servcodes':'',
           
           'Servcode CCAR %':(sub_values.servcode == 'CCAR').mean(),
           'Servcode CAR %' :(sub_values.servcode == 'CAR').mean(),
           'Servcode CGH0 %':(sub_values.servcode == 'CGH0').mean(),
           'Servcode HEP %':(sub_values.servcode == 'HEP').mean(),
           'Servcode MINT %':(sub_values.servcode == 'MINT').mean(),
           'Servcode NCHI %':(sub_values.servcode == 'NCHI').mean(),
           'Servcode SIMM %':(sub_values.servcode == 'SIMM').mean(),
           'Servcode BRUL %':(sub_values.servcode == 'BRUL').mean(),
           'Servcode CVP %':(sub_values.servcode == 'CVP').mean(),
           'Servcode PNEU %':(sub_values.servcode == 'PNEU').mean(),
           'Servcode CCAR':(sub_values.servcode == 'CCAR').sum(),
           'Servcode CAR' :(sub_values.servcode == 'CAR').sum(),
           'Servcode CGH0':(sub_values.servcode == 'CGH0').sum(),
           'Servcode HEP':(sub_values.servcode == 'HEP').sum(),
           'Servcode MINT':(sub_values.servcode == 'MINT').sum(),
           'Servcode NCHI':(sub_values.servcode == 'NCHI').sum(),
           'Servcode SIMM':(sub_values.servcode == 'SIMM').sum(),
           'Servcode BRUL':(sub_values.servcode == 'BRUL').sum(),
           'Servcode CVP':(sub_values.servcode == 'CVP').sum(),
           'Servcode PNEU':(sub_values.servcode == 'PNEU').sum(),
           'ICD10 Codes':'',
           chapters_ICD10[899] + ' %':(sub_ICD10.chapter_code == 899).mean(),
           chapters_ICD10[349] + ' %':(sub_ICD10.chapter_code == 349).mean(),
           chapters_ICD10[1095] + ' %':(sub_ICD10.chapter_code == 1095).mean(),
           chapters_ICD10[1988] + ' %':(sub_ICD10.chapter_code == 1988).mean(),
           chapters_ICD10[999] + ' %':(sub_ICD10.chapter_code == 999).mean(),
           chapters_ICD10[2699] + ' %':(sub_ICD10.chapter_code == 2699).mean(),
           chapters_ICD10[1799] + ' %':(sub_ICD10.chapter_code == 1799).mean(),
           chapters_ICD10[199] + ' %':(sub_ICD10.chapter_code == 199).mean(),
           chapters_ICD10[1399] + ' %':(sub_ICD10.chapter_code == 1399).mean(),
           chapters_ICD10[699] + ' %':(sub_ICD10.chapter_code == 699).mean(),
           chapters_ICD10[899]:(sub_ICD10.chapter_code == 899).sum(),
           chapters_ICD10[349]:(sub_ICD10.chapter_code == 349).sum(),
           chapters_ICD10[1095]:(sub_ICD10.chapter_code == 1095).sum(),
           chapters_ICD10[1988]:(sub_ICD10.chapter_code == 1988).sum(),
           chapters_ICD10[999]:(sub_ICD10.chapter_code == 999).sum(),
           chapters_ICD10[2699]:(sub_ICD10.chapter_code == 2699).sum(),
           chapters_ICD10[1799]:(sub_ICD10.chapter_code == 1799).sum(),
           chapters_ICD10[199]:(sub_ICD10.chapter_code == 199).sum(),
           chapters_ICD10[1399]:(sub_ICD10.chapter_code == 1399).sum(),
           chapters_ICD10[699]:(sub_ICD10.chapter_code == 699).sum(),
           'Disease of circulatory system subcodes':'',
           sub_chapters_ICD10[825] + ' %':(sub_ICD10[sub_ICD10.chapter_code == 899].sub_chapter_code == 825).mean(),
           sub_chapters_ICD10[852] + ' %':(sub_ICD10[sub_ICD10.chapter_code == 899].sub_chapter_code == 852).mean(),
           sub_chapters_ICD10[869] + ' %':(sub_ICD10[sub_ICD10.chapter_code == 899].sub_chapter_code == 869).mean(),
           sub_chapters_ICD10[879] + ' %':(sub_ICD10[sub_ICD10.chapter_code == 899].sub_chapter_code == 879).mean(),
           sub_chapters_ICD10[809] + ' %':(sub_ICD10[sub_ICD10.chapter_code == 899].sub_chapter_code == 809).mean(),
           sub_chapters_ICD10[825]:(sub_ICD10[sub_ICD10.chapter_code == 899].sub_chapter_code == 825).sum(),
           sub_chapters_ICD10[852]:(sub_ICD10[sub_ICD10.chapter_code == 899].sub_chapter_code == 852).sum(),
           sub_chapters_ICD10[869]:(sub_ICD10[sub_ICD10.chapter_code == 899].sub_chapter_code == 869).sum(),
           sub_chapters_ICD10[879]:(sub_ICD10[sub_ICD10.chapter_code == 899].sub_chapter_code == 879).sum(),
           sub_chapters_ICD10[809]:(sub_ICD10[sub_ICD10.chapter_code == 899].sub_chapter_code == 809).sum(),
           
           'Median length of stay [days]':sub_values.los.quantile(0.5),
           'IQR length of stay [days]':sub_values.los.quantile(0.75)-sub_values.los.quantile(0.25),
           
           'Death in ICU %':sub_values.death_in_icu.mean(),
           'Death in ICU':sub_values.death_in_icu.sum(),
           
           'Brain imaging%':sub_values.had_head_scan.mean(),
           'Brain imaging':sub_values.had_head_scan.sum(),
           
           'ACR as principal ID10':sub_ICD10.ACR_principalDx.mean(),
           'ACR in ICD10':sub_ICD10.ACR_in_all_Dx.mean() 
           }
    
    values_df.append(dic)

values_df = pd.DataFrame(values_df).transpose()

values_df.to_excel(output_folder + 'table_1.xls')


# %% ICD dictionnaries for chapters and sub-chapters
chapters_ICD10 = {    
199:'Certain infectious and parasitic diseases',
349:'Neoplasms',
389:'Diseases of the blood and blood-forming organs and certain disorders involving the immune mechanism',
489:'Endocrine, nutritional and metabolic diseases',
599:'Mental, Behavioral and Neurodevelopmental disorders',
699:'Diseases of the nervous system',
759:'Diseases of the eye and adnexa',
795:'Diseases of the ear and mastoid process',
899:'Diseases of the circulatory system',
999:'Diseases of the respiratory system',
1095:'Diseases of the digestive system',
1199:'Diseases of the skin and subcutaneous tissue',
1299:'Diseases of the musculoskeletal system and connective tissue',
1399:'Diseases of the genitourinary system',
1499:'Pregnancy, childbirth and the puerperium',
1596:'Certain conditions originating in the perinatal period',
1699:'Congenital malformations, deformations and chromosomal abnormalities',
1799:'Symptoms, signs and abnormal clinical and laboratory findings, not elsewhere classified',
1988:'Injury, poisoning and certain other consequences of external causes',
2085:'Codes for special purposes',
2499:'External causes of morbidity',
2699:'Factors influencing health status and contact with health services'}

sub_chapters_ICD10 = {
        9:"Intestinal infectious diseases", 
        19:"Tuberculosis", 
        28:"Certain zoonotic bacterial diseases", 
        49:"Other bacterial diseases", 
        64:"Infections with a predominantly sexual mode of transmission", 
        69:"Other spirochetal diseases", 
        74:"Other diseases caused by chlamydiae", 
        79:"Rickettsioses", 
        89:"Viral and prion infections of the central nervous system", 
        99:"Arthropod-borne viral fevers and viral hemorrhagic fevers", 
        109:"Viral infections characterized by skin and mucous membrane lesions", 
        110:"Other human herpesviruses", 
        119:"Viral hepatitis", 
        120:"Human immunodeficiency virus [HIV] disease", 
        134:"Other viral diseases", 
        149:"Mycoses", 
        164:"Protozoal diseases", 
        183:"Helminthiases", 
        189:"Pediculosis, acariasis and other infestations", 
        194:"Sequelae of infectious and parasitic diseases", 
        197:"Bacterial and viral infectious agents", 
        199:"Other infectious diseases", 
        214:"Malignant neoplasms of lip, oral cavity and pharynx", 
        226:"Malignant neoplasms of digestive organs", 
        239:"Malignant neoplasms of respiratory and intrathoracic organs", 
        241:"Malignant neoplasms of bone and articular cartilage", 
        244:"Melanoma and other malignant neoplasms of skin", 
        249:"Malignant neoplasms of mesothelial and soft tissue", 
        250:"Malignant neoplasms of breast", 
        258:"Malignant neoplasms of female genital organs", 
        263:"Malignant neoplasms of male genital organs", 
        268:"Malignant neoplasms of urinary tract", 
        272:"Malignant neoplasms of eye, brain and other parts of central nervous system", 
        275:"Malignant neoplasms of thyroid and other endocrine glands", 
        280:"Malignant neoplasms of ill-defined, other secondary and unspecified sites", 
        296:"Malignant neoplasms of lymphoid, hematopoietic and related tissue", 
        309:"In situ neoplasms", 
        336:"Benign neoplasms, except benign neuroendocrine tumors", 
        348:"Neoplasms of uncertain behavior, polycythemia vera and myelodysplastic syndromes", 
        349:"Neoplasms of unspecified behavior", 
        353:"Nutritional anemias", 
        359:"Hemolytic anemias", 
        364:"Aplastic and other anemias and other bone marrow failure syndromes", 
        369:"Coagulation defects, purpura and other hemorrhagic conditions", 
        377:"Other disorders of blood and blood-forming organs", 
        378:"Intraoperative and postprocedural complications of the spleen", 
        389:"Certain disorders involving the immune mechanism", 
        407:"Disorders of thyroid gland", 
        413:"Diabetes mellitus", 
        416:"Other disorders of glucose regulation and pancreatic internal secretion", 
        435:"Disorders of other endocrine glands", 
        436:"Intraoperative complications of endocrine system", 
        446:"Malnutrition", 
        464:"Other nutritional deficiencies", 
        468:"Overweight, obesity and other hyperalimentation", 
        488:"Metabolic disorders", 
        489:"Postprocedural endocrine and metabolic complications and disorders, not elsewhere classified", 
        509:"Mental disorders due to known physiological conditions", 
        519:"Mental and behavioral disorders due to psychoactive substance use", 
        529:"Schizophrenia, schizotypal, delusional,and other non-mood psychotic disorders", 
        539:"Mood [affective] disorders", 
        548:"Anxiety, dissociative, stress-related, somatoform and other nonpsychotic mental disorders", 
        559:"Behavioral syndromes associated with physiological disturbances and physical factors", 
        569:"Disorders of adult personality and behavior", 
        579:"Intellectual disabilities", 
        589:"Pervasive and specific developmental disorders", 
        598:"Behavioral and emotional disorders with onset usually occurring in childhood and adolescence", 
        599:"Unspecified mental disorder", 
        609:"Inflammatory diseases of the central nervous system", 
        614:"Systemic atrophies primarily affecting the central nervous system", 
        626:"Extrapyramidal and movement disorders", 
        632:"Other degenerative diseases of the nervous system", 
        637:"Demyelinating diseases of the central nervous system", 
        647:"Episodic and paroxysmal disorders", 
        659:"Nerve, nerve root and plexus disorders", 
        665:"Polyneuropathies and other disorders of the peripheral nervous system", 
        673:"Diseases of myoneural junction and muscle", 
        683:"Cerebral palsy and other paralytic syndromes", 
        699:"Other disorders of the nervous system", 
        705:"Disorders of eyelid, lacrimal system and orbit", 
        711:"Disorders of conjunctiva", 
        722:"Disorders of sclera, cornea, iris and ciliary body", 
        728:"Disorders of lens", 
        736:"Disorders of choroid and retina", 
        742:"Glaucoma", 
        744:"Disorders of vitreous body and globe", 
        747:"Disorders of optic nerve and visual pathways", 
        752:"Disorders of ocular muscles, binocular movement, accommodation and refraction", 
        754:"Visual disturbances and blindness", 
        757:"Other disorders of eye and adnexa", 
        759:"Intraoperative and postprocedural complications and disorders of eye and adnexa, not elsewhere classified", 
        762:"Diseases of external ear", 
        775:"Diseases of middle ear and mastoid", 
        783:"Diseases of inner ear", 
        794:"Other disorders of ear", 
        795:"Intraoperative and postprocedural complications and disorders of ear and mastoid process, not elsewhere classified", 
        802:"Acute rheumatic fever", 
        809:"Chronic rheumatic heart diseases", 
        815:"Hypertensive diseases", 
        825:"Ischemic heart diseases", 
        828:"Pulmonary heart disease and diseases of pulmonary circulation", 
        852:"Other forms of heart disease", 
        869:"Cerebrovascular diseases", 
        879:"Diseases of arteries, arterioles and capillaries", 
        889:"Diseases of veins,lymphatic vessels and lymph nodes, not elsewhere classified", 
        899:"Other and unspecified disorders of the circulatory system", 
        906:"Acute upper respiratory infections", 
        918:"Influenza and pneumonia", 
        922:"Other acute lower respiratory infections", 
        939:"Other diseases of upper respiratory tract", 
        947:"Chronic lower respiratory diseases", 
        970:"Lung diseases due to external agents", 
        984:"Other respiratory diseases principally affecting the interstitium", 
        986:"Suppurative and necrotic conditions of the lower respiratory tract", 
        994:"Other diseases of the pleura", 
        995:"Intraoperative and postprocedural complications and disorders of respiratory system, not elsewhere classified", 
        999:"Other diseases of the respiratory system", 
        1014:"Diseases of oral cavity and salivary glands", 
        1031:"Diseases of esophagus, stomach and duodenum", 
        1038:"Diseases of appendix", 
        1046:"Hernia", 
        1052:"Noninfective enteritis and colitis", 
        1064:"Other diseases of intestines", 
        1068:"Diseases of peritoneum and retroperitoneum", 
        1077:"Diseases of liver", 
        1087:"Disorders of gallbladder, biliary tract and pancreas", 
        1095:"Other diseases of the digestive system", 
        1108:"Infections of the skin and subcutaneous tissue", 
        1114:"Bullous disorders", 
        1130:"Dermatitis and eczema", 
        1145:"Papulosquamous disorders", 
        1154:"Urticaria and erythema", 
        1159:"Radiation-related disorders of the skin and subcutaneous tissue", 
        1175:"Disorders of skin appendages", 
        1176:"Intraoperative and postprocedural complications of skin and subcutaneous tissue", 
        1199:"Other disorders of the skin and subcutaneous tissue", 
        1202:"Infectious arthropathies", 
        1214:"Inflammatory polyarthropathies", 
        1219:"Osteoarthritis", 
        1225:"Other joint disorders", 
        1227:"Dentofacial anomalies [including malocclusion] and other disorders of jaw", 
        1236:"Systemic connective tissue disorders", 
        1243:"Deforming dorsopathies", 
        1249:"Spondylopathies", 
        1254:"Other dorsopathies", 
        1263:"Disorders of muscles", 
        1267:"Disorders of synovium and tendon", 
        1279:"Other soft tissue disorders", 
        1285:"Disorders of bone density and structure", 
        1290:"Other osteopathies", 
        1294:"Chondropathies", 
        1295:"Other disorders of the musculoskeletal system and connective tissue", 
        1296:"Intraoperative and postprocedural complications and disorders of musculoskeletal system, not elsewhere classified", 
        1299:"Biomechanical lesions, not elsewhere classified", 
        1308:"Glomerular diseases", 
        1316:"Renal tubulo-interstitial diseases", 
        1319:"Acute kidney failure and chronic kidney disease", 
        1323:"Urolithiasis", 
        1329:"Other disorders of kidney and ureter", 
        1339:"Other diseases of the urinary system", 
        1353:"Diseases of male genital organs", 
        1365:"Disorders of breast", 
        1377:"Inflammatory diseases of female pelvic organs", 
        1398:"Noninflammatory disorders of female genital tract", 
        1399:"Intraoperative and postprocedural complications and disorders of genitourinary system, not elsewhere classified", 
        1408:"Pregnancy with abortive outcome", 
        1409:"Supervision of high risk pregnancy", 
        1416:"Edema, proteinuria and hypertensive disorders in pregnancy, childbirth and the puerperium", 
        1429:"Other maternal disorders predominantly related to pregnancy", 
        1448:"Maternal care related to the fetus and amniotic cavity and possible delivery problems", 
        1477:"Complications of labor and delivery", 
        1482:"Encounter for delivery", 
        1492:"Complications predominantly related to the puerperium", 
        1504:"Newborn affected by maternal factors and by complications of pregnancy, labor, and delivery", 
        1508:"Disorders of newborn related to length of gestation and fetal growth", 
        1509:"Abnormal findings on neonatal screening", 
        1515:"Birth trauma", 
        1529:"Respiratory and cardiovascular disorders specific to the perinatal period", 
        1539:"Infections specific to the perinatal period", 
        1561:"Hemorrhagic and hematological disorders of newborn", 
        1574:"Transitory endocrine and metabolic disorders specific to newborn", 
        1578:"Digestive system disorders of newborn", 
        1583:"Conditions involving the integument and temperature regulation of newborn", 
        1584:"Other problems with newborn", 
        1596:"Other disorders originating in the perinatal period", 
        1607:"Congenital malformations of the nervous system", 
        1618:"Congenital malformations of eye, ear, face and neck", 
        1628:"Congenital malformations of the circulatory system", 
        1634:"Congenital malformations of the respiratory system", 
        1637:"Cleft lip and cleft palate", 
        1645:"Other congenital malformations of the digestive system", 
        1656:"Congenital malformations of genital organs", 
        1664:"Congenital malformations of the urinary system", 
        1679:"Congenital malformations and deformations of the musculoskeletal system", 
        1689:"Other congenital malformations", 
        1699:"Chromosomal abnormalities, not elsewhere classified", 
        1709:"Symptoms and signs involving the circulatory and respiratory systems", 
        1719:"Symptoms and signs involving the digestive system and abdomen", 
        1723:"Symptoms and signs involving the skin and subcutaneous tissue", 
        1729:"Symptoms and signs involving the nervous and musculoskeletal systems", 
        1739:"Symptoms and signs involving the genitourinary system", 
        1746:"Symptoms and signs involving cognition, perception, emotional state and behavior", 
        1749:"Symptoms and signs involving speech and voice", 
        1769:"General symptoms and signs", 
        1779:"Abnormal findings on examination of blood, without diagnosis", 
        1782:"Abnormal findings on examination of urine, without diagnosis", 
        1789:"Abnormal findings on examination of other body fluids, substances and tissues, without diagnosis", 
        1794:"Abnormal findings on diagnostic imaging and in function studies, without diagnosis", 
        1797:"Abnormal tumor markers", 
        1799:"Ill-defined and unknown cause of mortality", 
        1809:"Injuries to the head", 
        1819:"Injuries to the neck", 
        1829:"Injuries to the thorax", 
        1839:"Injuries to the abdomen, lower back, lumbar spine, pelvis and external genitals", 
        1849:"Injuries to the shoulder and upper arm", 
        1859:"Injuries to the elbow and forearm", 
        1869:"Injuries to the wrist, hand and fingers", 
        1879:"Injuries to the hip and thigh", 
        1889:"Injuries to the knee and lower leg", 
        1899:"Injuries to the ankle and foot", 
        1907:"Injuries involving multiple body regions", 
        1914:"Injury of unspecified body region", 
        1919:"Effects of foreign body entering through natural orifice", 
        1925:"Burns and corrosions of external body surface, specified by site", 
        1932:"Burns and corrosions",
        1934:"Frostbite", 
        1950:"Poisoning by, adverse effect of and underdosing of drugs, medicaments and biological substances", 
        1965:"Toxic effects of substances chiefly nonmedicinal as to source", 
        1978:"Other and unspecified effects of external causes", 
        1979:"Certain early complications of trauma", 
        1988:"Complications of surgical and medical care, not elsewhere classified", 
        2109:"Pedestrian injured in transport accident",
        2119:"Pedal cycle rider injured in transport accident", 
        2129:"Motorcycle rider injured in transport accident", 
        2139:"Occupant of three-wheeled motor vehicle injured in transport accident", 
        2149:"Car occupant injured in transport accident", 
        2159:"Occupant of pick-up truck or van injured in transport accident", 
        2169:"Occupant of heavy transport vehicle injured in transport accident", 
        2179:"Bus occupant injured in transport accident", 
        2189:"Other land transport accidents", 
        2194:"Water transport accidents", 
        2197:"Air and space transport accidents", 
        2199:"Other and unspecified transport accidents", 
        2219:"Slipping, tripping,stumbling and falls",
        2249:"Exposure to inanimate mechanical forces", 
        2264:"Exposure to animate mechanical forces", 
        2274:"Accidental non-transport drowning and submersion", 
        2299:"Exposure to electric current, radiation and extreme ambient air temperature and pressure", 
        2308:"Exposure to smoke, fire and flames", 
        2319:"Contact with heat and hot substances", 
        2339:"Exposure to forces of nature", 
        2358:"Accidental exposure to other specified factors", 
        2383:"Intentional self-harm", 
        2408:"Assault", 
        2433:"Event of undetermined intent", 
        2438:"Legal intervention, operations of war, military operations, and terrorism", 
        2469:"Misadventures to patients during surgical and medical care", 
        2484:"Complications of medical and surgical care",  
        2499:"Supplementary factors related to causes of morbidity classified elsewhere", 
        2513:"Persons encountering health services for examinations", 
        2515:"Genetic carrier and genetic susceptibility to disease", 
        2516:"Resistance to antimicrobial drugs", 
        2517:"Estrogen receptor status", 
        2518:"Retained foreign body fragments", 
        2528:"Persons with potential health hazards related to communicable diseases", 
        2539:"Persons encountering health services in circumstances related to reproduction", 
        2553:"Encounters for other specific health care", 
        2565:"Persons with potential health hazards related to socioeconomic and psychosocial circumstances", 
        2566:"Do not resuscitate status", 
        2567:"Blood type", 
        2568:"Body mass index (BMI)", 
        2576:"Persons encountering health services in other circumstances", 
        2600:"Persons with potential health hazards related to family and personal history and certain conditions influencing health status"
        }